### ISSUE TITLE
pytest.PLATFORM does not exists

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#40] opened 2015-05-11 21:56 UTC
unhandled exception occurred while testing test_bridge
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/logilab/common/pytest.py", line 440, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python2.7/site-packages/logilab/common/pytest.py", line 756, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python2.7/unittest/main.py", line 77, in __init__
    self.module = __import__(module)
  File "test_bridge.py", line 6, in <module>
    if pytest.PLATFORM == "win32":
AttributeError: 'module' object has no attribute 'PLATFORM'

**Comment by prologic** [comment] 2015-05-11 22:17
Hmm that's odd it should exist!

**Comment by prologic** [comment] 2015-05-11 23:16
It's defiantly there:

```#!bash
prologic@daisy
Tue May 12 09:19:02 
~/circuits
$ grin PLATFORM
./examples/testing/pytest/conftest.py:
  114 :         ("PLATFORM", sys.platform),
./tests/app/test_daemon.py:
    5 : if pytest.PLATFORM == "win32":
./tests/conftest.py:
  154 :         ("PLATFORM", sys.platform),
./tests/core/test_bridge.py:
    6 : if pytest.PLATFORM == "win32":
./tests/io/test_file.py:
    4 : if pytest.PLATFORM == "win32":
./tests/io/test_process.py:
    4 : if pytest.PLATFORM == "win32":
./tests/net/test_pipe.py:
    4 : if pytest.PLATFORM == "win32":
./tests/net/test_tcp.py:
   91 :     if pytest.PLATFORM == "win32" and pytest.PYVER[:2] >= (3, 2):
  149 :     if pytest.PLATFORM == "win32":
  254 :         if pytest.PLATFORM == "win32":
./tests/node/test_node.py:
    4 : from pytest import fixture, skip, PLATFORM
    7 : if PLATFORM == 'win32':
./tests/node/test_protocol.py:
    4 : from pytest import fixture, skip, PLATFORM
    9 : if PLATFORM == 'win32':
./tests/node/test_server.py:
    4 : from pytest import PLATFORM, skip, fixture
   11 : if PLATFORM == 'win32':
./tests/web/test_servers.py:
  108 :     if pytest.PLATFORM == "win32":
```

**Comment by prologic** [comment] 2015-05-11 23:16
See: [tests.conftest#PLATFORM](https://github.com/circuits/circuits/blob/master/tests/conftest.py#L154)

How are you running this test?

**Comment by spaceone** [comment] 2015-05-11 23:17
py.test2.7 *.py, which pytest version?

**Comment by prologic** [comment] 2015-05-11 23:19
```#!bash
(circuits)
prologic@daisy
Tue May 12 09:22:02 
~/circuits
$ py.test --version
This is pytest version 2.5.2, imported from /home/prologic/.virtualenvs/circuits/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  pytest-cov-1.6 at /home/prologic/.virtualenvs/circuits/lib/python2.7/site-packages/pytest_cov.pyc
```

Only thing I can think of is the way you define ``pytest.<CONSTANT|FUNCTION>`` has changed?

**Comment by spaceone** [comment] 2015-05-11 23:20
I have got pytest 2.3.4.

**Comment by prologic** [comment] 2015-05-11 23:22
Try to upgrade? :)

**Comment by spaceone** [comment] 2015-05-11 23:24
event with pytest 2.7-0 (from official archlinux repositories) I got the same exception

**Comment by prologic** [comment] 2015-05-11 23:25
You are using a virtualenv right? :)

**Comment by spaceone** [comment] 2015-05-11 23:26
no

**Comment by prologic** [comment] 2015-05-11 23:26
Looking at your original traceback; it doesn't look quite right. Not quite what I'd expect from a fresh virtualenv dev environment with circuits and pytest.

**Comment by prologic** [comment] 2015-05-11 23:26
You should be :) -- Best practise et all :)

**Comment by spaceone** [comment] 2015-05-11 23:26
this sucks... please provide a manual with all necessary steps to run the tests...

**Comment by prologic** [comment] 2015-05-11 23:27
Can't guarantee things work as expected if you don't use a virtualenv and the requirements*.txt in the repo as laid out :)

**Comment by prologic** [comment] 2015-05-11 23:27
```#!bash
pip install virtualenvwrapper
source $(which virtualenvwrapper.sh)
mkvirtualenv circuits
pip install -r requirements-dev.txt
```

**Comment by prologic** [comment] 2015-05-11 23:29
See: http://circuits.readthedocs.org/en/latest/dev/index.html

But I admit we don't seem to have a document on how to setup a "proper" development environment -- It's been "assumed" :)

**Comment by prologic** [comment] 2015-05-12 00:02
Just FYI; tests run fine here locally :)

```#!bash
(circuits)
prologic@daisy
Tue May 12 10:00:49 
~/circuits
$ py.test tests
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.9 -- py-1.4.23 -- pytest-2.5.2
plugins: cov
collected 295 items 

tests/app/test_daemon.py .
tests/core/test_bridge.py .
tests/core/test_call_wait.py .....
tests/core/test_call_wait_order.py .
tests/core/test_call_wait_timeout.py ....
tests/core/test_channel_selection.py .
tests/core/test_complete.py ..
tests/core/test_component_repr.py ..
tests/core/test_component_setup.py ...
tests/core/test_component_targeting.py .
tests/core/test_core.py ..
tests/core/test_debugger.py ........
tests/core/test_dynamic_handlers.py ..
tests/core/test_errors.py .
tests/core/test_event.py .....
tests/core/test_event_priority.py ..
tests/core/test_feedback.py ..
tests/core/test_filters.py .
tests/core/test_generate_events.py .
tests/core/test_generator_value.py ..
tests/core/test_globals.py ...
tests/core/test_imports.py .
tests/core/test_inheritence.py ..
tests/core/test_interface_query.py ....
tests/core/test_loader.py .
tests/core/test_manager_repr.py .
tests/core/test_new_filter.py ..
tests/core/test_priority.py .
tests/core/test_signals.py .
tests/core/test_timers.py ...
tests/core/test_utils.py ....
tests/core/test_value.py ......
tests/core/test_worker_process.py ...
tests/core/test_worker_thread.py ..
tests/io/test_file.py ..
tests/io/test_notify.py .
tests/io/test_process.py ..
tests/net/test_client.py ...
tests/net/test_pipe.py .
tests/net/test_poller_reuse.py .
tests/net/test_tcp.py ..............................
tests/net/test_udp.py ............
tests/net/test_unix.py ...
tests/node/test_node.py .
tests/node/test_protocol.py ......
tests/node/test_server.py ....
tests/node/test_utils.py ..
tests/protocols/test_irc.py .............................
tests/protocols/test_line.py ..
tests/tools/test_tools.py .......
tests/web/test_bad_requests.py .
tests/web/test_basicauth.py .
tests/web/test_call_wait.py .
tests/web/test_client.py .
tests/web/test_conn.py .
tests/web/test_cookies.py .
tests/web/test_core.py ..........
tests/web/test_digestauth.py .
tests/web/test_dispatcher.py ....
tests/web/test_dispatcher2.py ......
tests/web/test_dispatcher3.py ....
tests/web/test_disps.py .
tests/web/test_exceptions.py ....
tests/web/test_expires.py ..
tests/web/test_expose.py .
tests/web/test_generator.py .
tests/web/test_gzip.py ..
tests/web/test_headers.py ....
tests/web/test_http.py .
tests/web/test_json.py ..
tests/web/test_jsonrpc.py .
tests/web/test_large_post.py .
tests/web/test_logger.py ...
tests/web/test_methods.py ..
tests/web/test_multipartformdata.py ..
tests/web/test_null_response.py .
tests/web/test_request_failure.py .
tests/web/test_security.py ...
tests/web/test_serve_download.py .
tests/web/test_serve_file.py .
tests/web/test_servers.py .....
tests/web/test_sessions.py .
tests/web/test_static.py ..........
tests/web/test_unicode.py .....
tests/web/test_utils.py ..
tests/web/test_value.py .
tests/web/test_vpath_args.py .
tests/web/test_websockets.py .
tests/web/test_wsgi_application.py ......
tests/web/test_wsgi_application_generator.py .
tests/web/test_wsgi_application_yield.py .
tests/web/test_wsgi_gateway.py .
tests/web/test_wsgi_gateway_errors.py .
tests/web/test_wsgi_gateway_generator.py .
tests/web/test_wsgi_gateway_multiple_apps.py .
tests/web/test_wsgi_gateway_null_response.py .
tests/web/test_wsgi_gateway_write.py .
tests/web/test_wsgi_gateway_yield.py .
tests/web/test_xmlrpc.py .
tests/web/test_yield.py .

============================================= 295 passed in 103.28 seconds =============================================
```

What's even more amazing is that they all pass too :)

**Comment by prologic** [comment] 2015-05-23 06:58
Closing this as "cannot reproduce" ; Possible cause #41

**Closed by prologic** 2015-05-23 06:58 UTC
