### ISSUE TITLE
Experiencing buffer issues when using SSL with web module

### ISSUE THREAD

**Issue by Ryan-Gordon1** [circuits/circuits#270] opened 2019-06-27 14:49 UTC
When using circuits I am trying to create a component which will take in requests and their respective payloads, kind of like a webhook. At the moment this works no problem when not using SSL. However if SSL is used we encounter a SSLWantReadError
`<error[web] (<ssl.SSLSocket object at 0x7f7651964de8>, SSLWantReadError(2, u'The operation did not complete (read) (_ssl.c:1822)') )>​`

When using plain WS, data is taken from the socket using recv(). However when using WSS it appears data taken using a read()

I have been trying to find the root cause for this and am currently thinking this might be it. 
https://github.com/circuits/circuits/blob/00bede3a479789191521bfe7c909c4422bfe089a/circuits/net/sockets.py#L188

If you check the git blame for that file you'll notice a few lines below we use `recv()` and that change was brought in a couple years ago. If you check the commit message it mentions what looks like the exact same issue, can we bring the change to line 188 also ?

**Comment by spaceone** [comment] 2019-06-27 15:08
@Ryan-Gordon1 Thanks! Could you verify that my patch https://github.com/circuits/circuits/commit/cce61af7cdea9613cbaf68b0eeb3119ade44481e works for you?

**Comment by Ryan-Gordon1** [comment] 2019-07-24 14:50
Coming back to you on this. This was a logical change but sadly the issue appears to still be there. We have noticed that if we change the bufsize param we can make it work with SSL but this is only a temporary measure unless you are comfortable setting bufsize to some large value. 

I have submitted a PR for this #273 which allows us to set that bufsize but there may be some other underlying problem here.

**Comment by jksecurity** [comment] 2019-08-20 07:20
I have managed to resolve this issue in house. I have sent my solution to the IBM Resilient support helpdesk who should be in contact with some of the devs of circuits. I am expecting a PR with my code very soon.

The issue is actually not related to the buffer size, but to the way the socket is read when SSL is enabled.

**Comment by spaceone** [comment] 2020-11-02 23:54
@jeromekleinen We did not receive a PR or any information yet. Can you give them?

**Comment by spaceone** [comment] 2021-08-20 17:34
@jeromekleinen ping

**Comment by spaceone** [comment] 2021-08-20 20:42
Looks like it's fixed by 8962871acbd9152d0eda58234993572d7d04afd1.

**Closed by spaceone** 2021-08-20 20:42 UTC
